# Generated by Django 5.1.4 on 2025-03-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_scan_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
