# Generated by Django 5.1.4 on 2025-05-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_totp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totp',
            name='secret',
            field=models.CharField(max_length=32),
        ),
    ]
